apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    name: arao-label
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: arao-label
    spec:
      containers:
        - name: nginx-demo
          image: nginx:1.16
      nodeSelector:
        name: arao-label
  replicas: 3
  selector:
    matchLabels:
      name: arao-label

