apiVersion: apps/v1
kind: Deployment
metadata:
  name: arao-app
  labels:
    name: arao-label
    type: back-end
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: arao-app
      labels:
        name: arao-label
        type: back-end
    spec:
      containers:
        - name: arao-app
          image: kulbhushanmayer/genesys:1.0
      nodeSelector:
        name: arao-label
        type: back-end
  replicas: 3
  selector:
    matchLabels:
      name: arao-label
      type: back-end

