apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-and-pod-log-reader
  namespace: arvind
rules:
  - apiGroups: [""] # "" indicates the code API group
    resources: ["pod", "deployment"]
    verbs: ["get", "list"]

