apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: arvind
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the code API group
    resources: ["pods"]
    verbs: ["get", "watch", list]
