apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  labels:
    name: arao-label
    type: back-end
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
  containers:
  - name: ssh-test-container
    image: httpd
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
