apiVersion: v1
kind: Pod
metadata:
  name: arao-demo
  labels:
    name: arao-label
    type: back-end
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: user.txt
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: pass.txt
