apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #clusterRoles and not namespaced
  name: arvindRole
  labels:
    k8s-app: kubernetes-dashboard
  namespace: kubernetes-dashboard
rules:
  - apiGroups: [""] # "" indicates the code API group
    resources: ["pods"]
    verbs: ["get", "update", "list"]

