apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arvindRoleBinding
  labels:
    k8s-app: kubernetes-dashboard
  namespace: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arvindRole
subjects:
  - kind: ServiceAccount
    name: arvind
    namespace: kubernetes-dashboard

